import kotlin.ArithmeticException
//
fun main(args: Array<String>) {
//    counter(2,"goals")
//
////    arrays
//    var countries= mutableListOf<String>()
//    countries.add("Kenya")
//    countries.add("Uganda")
//    countries.add("Tanzania")
//    countries.add("Rwanda")
//
//    for (i in 0..countries.size-1){
//       println(countries[i])
//    }
////    lambda example
//    countries.forEach{country->
//        println(country)
//    }
//
//}
//fun counter(count:Int,name:String){
//    println("The count of $name is ${count+1}")
//    divideTwoNumbers(num = 10,num2 = 0)
//    println("Another Function")
}
//fun divideTwoNumbers(num:Int,num2:Int){
//    try {
//        var result=num/num2
//        println("$num/$num2=$result")
//    }catch (e:ArithmeticException){
//    println(e)}
//}


//lambda function
//its an anonymous function bcoz it has no name